# -*- coding: utf-8 -*-
# Developed by Bizople Solutions Pvt. Ltd.
# See LICENSE file for full copyright and licensing details

{
    'name': 'Theme Vouge',
    'category': 'Theme/eCommerce',
    'version': '15.0.1.4',
    'author': 'Bizople Solutions Pvt. Ltd.',
    'website': 'https://www.bizople.com',
    'summary': 'Theme Vouge is featured with eCommerce functionalities and fully responsive to all devices. Theme Vouge is perfect for any Industry like electronics, fashion, furniture, grocery, etc, it will work for any Industry.',
    'description': """Theme Vouge is featured with eCommerce functionalities and fully responsive to all devices. Theme Vouge can be used to take your store online with attractive and eye catching design. Theme Vouge is perfect for any category store like electronics, fashion, furniture, grocery, etc, it will work for any category.""",
    'depends': [
        'base',
        'website',
        'website_blog',
        'portal',
        'theme_default',
        'web_editor',
        'sale',
        'website_sale',
        'website_sale_wishlist',
        'website_sale_comparison',
        'vouge_theme_common',
    ],
    'data': [
        'views/assets.xml',
        'views/theme_vouge_inherited.xml',
        'views/coming_soon_template.xml',
        'views/404_template.xml',
        'views/thankyou_template.xml',
        'views/product_banner_options.xml',
        'views/image_hotspot_options.xml',
        'views/snippets/s_image_hotspot.xml',
        'views/product_configurator_options.xml',
        'views/category_configurator_options.xml',
        'views/brand_configurator_options.xml',
        'views/shop_page_template.xml',
        'views/product_page_template.xml',
        'views/product_per_page_view.xml',
        'views/product_customize_template.xml',
        'views/website_heighlight_template.xml',
        'views/dynamicslider.xml',
        'views/res_config.xml',
        'views/slider_snippets.xml',
        'views/product_tab_view.xml',
        'views/brand_view.xml',
        'views/pwa_shortcuts.xml',
        'views/product_quick_view_template.xml',
        'views/product_service_view.xml',
        'views/common_template.xml',
        'views/customize_inherit.xml',
        # 'views/newsletter_popup_inherit.xml',
        'views/shop_cart_sidebar.xml',
        'views/portal_template.xml',
        'views/help_center_template.xml',
        'views/wishlist_inherited.xml',
        'views/blog_page_inherit.xml',
        'views/product_rating_shop_page.xml',
        'views/theme_vouge_search.xml',
        'views/menus.xml',
        'views/sale_portal_templates_inherit.xml',

        # Inherited
        'views/inherited/contact_us_template.xml',
        'views/inherited/login_template_inherited.xml',

        # Headers
        'views/headers/header_template1.xml',
        'views/headers/header_template2.xml',
        'views/headers/header_template3.xml',
        'views/headers/header_template4.xml',
        'views/headers/header_template5.xml',
        'views/headers/header_template6.xml',
        'views/headers/header_template7.xml',
        'views/headers/header_template8.xml',
        'views/headers/header_template9.xml',
        'views/headers/header_template10.xml',
        'views/headers/header_template11.xml',

        # Footers
        'views/footers/footer_template1.xml',
        'views/footers/footer_template2.xml',
        'views/footers/footer_template3.xml',
        'views/footers/footer_template4.xml',
        'views/footers/footer_template5.xml',
        'views/footers/footer_template6.xml',
        'views/footers/footer_template7.xml',
        'views/footers/footer_template8.xml',

        # Snippets
        # Dynamic Snippets
        'views/snippets/blocks1.xml',
        'views/snippets/blocks2.xml',
        'views/snippets/blocks3.xml',
        'views/snippets/blocks4.xml',
        'views/snippets/blocks5.xml',
        'views/snippets/blocks6.xml',
        'views/snippets/blocks7.xml',
        'views/snippets/s_configurator_snippet_style2.xml',
        'views/snippets/s_configurator_snippet_style3.xml',
        'views/snippets/s_configurator_snippet_style4.xml',

        # E-commerce Full Pages
        'views/snippets/s_fashion_snippet.xml',
        'views/snippets/s_fashion_accesories_snippet.xml',
        'views/snippets/s_furniture_snippet.xml',
        'views/snippets/s_wine_snippet.xml',
        'views/snippets/s_electronic_snippet.xml',
        'views/snippets/s_tools_snippet.xml',
        'views/snippets/s_restaurant_snippet.xml',
        'views/snippets/s_autoparts_snippet.xml',
        'views/snippets/s_medical_equipement_snippet.xml',
        'views/snippets/s_sports_snippet.xml',
        'views/snippets/s_glasses_snippet.xml',
        'views/snippets/s_spa_snippet.xml',
        'views/snippets/s_grocery_snippet.xml',
        'views/snippets/s_organic_snippet.xml',
        'views/snippets/s_jewellery_snippet.xml',
        'views/snippets/s_homepage_drone.xml',
        'views/snippets/s_homepage_stroller.xml',
        'views/snippets/s_homepage_watch.xml',
        'views/snippets/s_homepage_scooter.xml',
        'views/snippets/s_homepage_health.xml',
        'views/snippets/s_homepage_backpack.xml',
        'views/snippets/s_homepage_shoes.xml',
        'views/snippets/s_homepage_jewellery.xml',
        'views/snippets/s_homepage_headphones.xml',
        'views/snippets/s_homepage_bike.xml',
        'views/snippets/s_homepage_wallet.xml',
        'views/snippets/s_homepage_coffeemaker.xml',
        'views/snippets/s_homepage_energydrink.xml',
        'views/snippets/s_homepage_bag.xml',
        'views/snippets/s_homepage_shaver.xml',

        'views/snippets/s_homepage1_home_banner.xml',
        'views/snippets/s_homepage1_service.xml',
        'views/snippets/s_homepage1_cam_info.xml',
        'views/snippets/s_homepage1_parallax.xml',
        'views/snippets/s_homepage1_testimonial.xml',
        'views/snippets/s_homepage1_screen_info.xml',
        'views/snippets/s_homepage1_subscribe.xml',

        'views/snippets/homapage1_newsletter.xml',
        'views/snippets/homepage1_advertisement.xml',
        'views/snippets/homepage1_banner.xml',
        'views/snippets/homepage1_featured_services.xml',
        'views/snippets/homepage2_banner.xml',

        'views/snippets/s_homepage2_home_banner.xml',
        'views/snippets/s_homepage2_feature_row.xml',
        'views/snippets/s_homepage2_introduction.xml',
        'views/snippets/s_homepage2_single_product.xml',
        'views/snippets/s_homepage2_testimonial.xml',
        'views/snippets/s_homepage2_parallax.xml',
        'views/snippets/s_homepage2_subscribe.xml',

        'views/snippets/s_homepage3_home_banner.xml',
        'views/snippets/s_homepage3_feature_row.xml',
        'views/snippets/s_homepage3_about_us.xml',
        'views/snippets/s_homepage3_feature.xml',
        'views/snippets/s_homepage3_product_feature.xml',
        'views/snippets/s_homepage3_tech_specs.xml',
        'views/snippets/s_homepage3_testimonial.xml',
        'views/snippets/s_homepage3_client_row.xml',
        'views/snippets/s_homepage3_subscribe.xml',

        'views/snippets/s_homepage4_home_banner.xml',
        'views/snippets/s_homepage4_feature_row.xml',
        'views/snippets/s_homepage4_about_us.xml',
        'views/snippets/s_homepage4_single_product.xml',
        'views/snippets/s_homepage4_tech_specs.xml',
        'views/snippets/s_homepage4_testimonial.xml',
        'views/snippets/s_homepage4_subscribe.xml',

        'views/snippets/s_homepage5_home_banner.xml',
        'views/snippets/s_homepage5_feature_row.xml',
        'views/snippets/s_homepage5_single_product.xml',
        'views/snippets/s_homepage5_testimonial.xml',
        'views/snippets/s_homepage5_subscribe.xml',

        'views/snippets/s_homepage6_home_banner.xml',
        'views/snippets/s_homepage6_feature.xml',
        'views/snippets/s_homepage6_feature_row.xml',
        'views/snippets/s_homepage6_product_info.xml',
        'views/snippets/s_homepage6_product_feature.xml',
        'views/snippets/s_homepage6_testimonial.xml',
        'views/snippets/s_homepage6_subscribe.xml',

        'views/snippets/s_homepage7_home_banner.xml',
        'views/snippets/s_homepage7_about_us.xml',
        'views/snippets/s_homepage7_product_feature.xml',
        'views/snippets/s_homepage7_feature.xml',
        'views/snippets/s_homepage7_testimonial.xml',
        'views/snippets/s_homepage7_parallax.xml',
        'views/snippets/s_homepage7_preorder.xml',
        'views/snippets/s_homepage7_feature_row.xml',
        'views/snippets/s_homepage7_subscribe.xml',

        'views/snippets/s_homepage8_home_banner.xml',
        'views/snippets/s_homepage8_about_us.xml',
        'views/snippets/s_homepage8_single_product.xml',
        'views/snippets/s_homepage8_product_feature.xml',
        'views/snippets/s_homepage8_testimonial.xml',
        'views/snippets/s_homepage8_feature_row.xml',
        'views/snippets/s_homepage8_video.xml',
        'views/snippets/s_homepage8_subscribe.xml',

        'views/snippets/s_homepage9_home_banner.xml',
        'views/snippets/s_homepage9_product_feature.xml',
        'views/snippets/s_homepage9_feature_row.xml',
        'views/snippets/s_homepage9_parallax.xml',
        'views/snippets/s_homepage9_feature.xml',
        'views/snippets/s_homepage9_product_info.xml',
        'views/snippets/s_homepage9_testimonial.xml',
        'views/snippets/s_homepage9_subscribe.xml',

        'views/snippets/s_homepage10_home_banner.xml',
        'views/snippets/s_homepage10_feature_row.xml',
        'views/snippets/s_homepage10_about_us.xml',
        'views/snippets/s_homepage10_core_feature.xml',
        'views/snippets/s_homepage10_testimonial.xml',
        'views/snippets/s_homepage10_sale.xml',
        'views/snippets/s_homepage10_subscribe.xml',

        'views/snippets/s_homepage11_home_banner.xml',
        'views/snippets/s_homepage11_introduction.xml',
        'views/snippets/s_homepage11_single_product.xml',
        'views/snippets/s_homepage11_product_feature.xml',
        'views/snippets/s_homepage11_feature_row.xml',
        'views/snippets/s_homepage11_testimonial.xml',
        'views/snippets/s_homepage11_subscribe.xml',

        'views/snippets/s_homepage12_home_banner.xml',
        'views/snippets/s_homepage12_feature_row.xml',
        'views/snippets/s_homepage12_introduction.xml',
        'views/snippets/s_homepage12_single_product.xml',
        'views/snippets/s_homepage12_discount.xml',
        'views/snippets/s_homepage12_testimonial.xml',
        'views/snippets/s_homepage12_subscribe.xml',

        'views/snippets/s_homepage13_home_banner.xml',
        'views/snippets/s_homepage13_feature_row.xml',
        'views/snippets/s_homepage13_feature.xml',
        'views/snippets/s_homepage13_single_product.xml',
        'views/snippets/s_homepage13_tech_specs.xml',
        'views/snippets/s_homepage13_testimonial.xml',
        'views/snippets/s_homepage13_subscribe.xml',

        'views/snippets/s_homepage14_home_banner.xml',
        'views/snippets/s_homepage14_about_us.xml',
        'views/snippets/s_homepage14_feature_row.xml',
        'views/snippets/s_homepage14_product_info.xml',
        'views/snippets/s_homepage14_feature.xml',
        'views/snippets/s_homepage14_introduction.xml',
        'views/snippets/s_homepage14_testimonial.xml',
        'views/snippets/s_homepage14_client_row.xml',
        'views/snippets/s_homepage14_subscribe.xml',

        'views/snippets/s_homepage15_home_banner.xml',
        'views/snippets/s_homepage15_feature_row.xml',
        'views/snippets/s_homepage15_product_image.xml',
        'views/snippets/s_homepage15_product_info.xml',
        'views/snippets/s_homepage15_discount.xml',
        'views/snippets/s_homepage15_testimonial.xml',
        'views/snippets/s_homepage15_product_guide.xml',
        'views/snippets/s_homepage15_feature.xml',
        'views/snippets/s_homepage15_client_row.xml',
        'views/snippets/s_homepage15_subscribe.xml',

        'views/product_size_chart_view.xml',


        # Business Full Pages
        'views/snippets/s_charity_snippet.xml',
        'views/snippets/s_it_solution_snippet.xml',
        'views/snippets/s_creative_agency_snippet.xml',
        'views/snippets/s_app_landing_one_snippet.xml',
        'views/snippets/s_app_landing_two_snippet.xml',
        'views/snippets/s_medical_snippet.xml',
        'views/snippets/s_snowboard_ski_snippet.xml',
        'views/snippets/s_cyber_security_snippet.xml',
        'views/snippets/s_real_estate_snippet.xml',
        'views/snippets/s_travel_snippet.xml',
        'views/snippets/s_yoga_snippet.xml',
        'views/snippets/s_seo_snippet.xml',
        'views/snippets/s_hotel_snippet.xml',
        'views/snippets/s_dessert_snippet.xml',

        # Fashion
        'views/snippets/s_fashion_banner.xml',
        'views/snippets/s_fashion_service.xml',
        'views/snippets/s_fashion_sale.xml',
        'views/snippets/s_fashion_arrival.xml',
        'views/snippets/s_fashion_deal.xml',
        'views/snippets/s_fashion_instagram.xml',
        'views/snippets/s_fashion_brand.xml',

        # Fashion Accesories
        'views/snippets/s_fashion_accesories_banner.xml',
        'views/snippets/s_fashion_accesories_products.xml',
        'views/snippets/s_fashion_accesories_sale.xml',
        'views/snippets/s_fashion_accesories_collection.xml',
        'views/snippets/s_fashion_accesories_service.xml',

        # Furniture
        'views/snippets/s_furniture_banner.xml',
        'views/snippets/s_furniture_products.xml',
        'views/snippets/s_furniture_sale.xml',
        'views/snippets/s_furniture_service.xml',
        'views/snippets/s_furniture_clients.xml',

        # Wine
        'views/snippets/s_wine_banner.xml',
        'views/snippets/s_wine_service.xml',
        'views/snippets/s_wine_famous.xml',
        'views/snippets/s_wine_winemakers.xml',
        'views/snippets/s_wine_varieties.xml',
        'views/snippets/s_wine_vineyards.xml',

        # Electronics
        'views/snippets/s_electronic_banner.xml',
        'views/snippets/s_electronic_accesories.xml',
        'views/snippets/s_electronic_products.xml',
        'views/snippets/s_electronic_brands.xml',
        'views/snippets/s_electronic_gallery.xml',

        # Tools
        'views/snippets/s_tools_banner.xml',
        'views/snippets/s_tools_service.xml',
        'views/snippets/s_tools_sale.xml',
        'views/snippets/s_tools_offer.xml',

        # Restaurant
        'views/snippets/s_restaurant_banner.xml',
        'views/snippets/s_restaurant_flavour.xml',
        'views/snippets/s_restaurant_offer.xml',
        'views/snippets/s_restaurant_image_counter.xml',
        'views/snippets/s_restaurant_dishes.xml',
        'views/snippets/s_restaurant_service.xml',
        'views/snippets/s_restaurant_combo.xml',

        # Autoparts
        'views/snippets/s_autoparts_banner.xml',
        'views/snippets/s_autoparts_service.xml',
        'views/snippets/s_autoparts_images.xml',
        'views/snippets/s_autoparts_sale.xml',
        'views/snippets/s_autoparts_brands.xml',

        # Medical Equipement
        'views/snippets/s_medical_equipement_banner.xml',
        'views/snippets/s_medical_equipement_durability.xml',
        'views/snippets/s_medical_equipement_prevention.xml',
        'views/snippets/s_medical_equipement_testimonial.xml',

        # Medical Equipement
        'views/snippets/s_sports_banner.xml',
        'views/snippets/s_sports_brands.xml',
        'views/snippets/s_sports_collection.xml',
        'views/snippets/s_sports_sale_banner.xml',
        'views/snippets/s_sports_story.xml',

        # Glasses
        'views/snippets/s_glasses_banner.xml',
        'views/snippets/s_glasses_history.xml',
        'views/snippets/s_glasses_image_text.xml',
        'views/snippets/s_glasses_features.xml',
        'views/snippets/s_glasses_collection.xml',

        # Spa
        'views/snippets/s_spa_banner.xml',
        'views/snippets/s_spa_service.xml',
        'views/snippets/s_spa_inspiration.xml',
        'views/snippets/s_spa_single_banner.xml',
        'views/snippets/s_spa_testimonial.xml',

        # Grocery
        'views/snippets/s_grocery_banner.xml',
        'views/snippets/s_grocery_deals.xml',
        'views/snippets/s_grocery_testimonial.xml',
        'views/snippets/s_grocery_service.xml',
        'views/snippets/s_grocery_delivery.xml',
        'views/snippets/s_grocery_brands.xml',

        # Organic
        'views/snippets/s_organic_banner.xml',
        'views/snippets/s_organic_products.xml',
        'views/snippets/s_organic_service.xml',
        'views/snippets/s_organic_welcome.xml',
        'views/snippets/s_organic_questions.xml',
        'views/snippets/s_organic_customers.xml',
        'views/snippets/s_organic_newsletter.xml',

        # Jewellery
        'views/snippets/s_jewellery_banner.xml',
        'views/snippets/s_jewellery_welcome_shop.xml',
        'views/snippets/s_jewellery_deals.xml',
        'views/snippets/s_jewellery_brands.xml',
        'views/snippets/s_jewellery_collection.xml',
        'views/snippets/s_jewellery_customers.xml',

        # Charity
        'views/snippets/s_charity_banner.xml',
        'views/snippets/s_charity_aboutus.xml',
        'views/snippets/s_charity_mission.xml',
        'views/snippets/s_charity_campaigns.xml',
        'views/snippets/s_charity_help.xml',
        'views/snippets/s_charity_newsletter.xml',
        'views/snippets/s_charity_team.xml',
        'views/snippets/s_charity_counter.xml',

        # IT Solution
        'views/snippets/s_it_solution_banner.xml',
        'views/snippets/s_it_solution_service.xml',
        'views/snippets/s_it_solution_counter.xml',
        'views/snippets/s_it_solution_software.xml',
        'views/snippets/s_it_solution_work.xml',
        'views/snippets/s_it_solution_case_studies.xml',
        'views/snippets/s_it_solution_pricing_plan.xml',
        'views/snippets/s_it_solution_clients.xml',
        'views/snippets/s_it_solution_brands.xml',
        'views/snippets/s_it_solution_contactus.xml',

        # Creative Agency
        'views/snippets/s_creative_agency_banner.xml',
        'views/snippets/s_creative_agency_service.xml',
        'views/snippets/s_creative_agency_projects.xml',
        'views/snippets/s_creative_agency_rewards.xml',
        'views/snippets/s_creative_agency_counter.xml',
        'views/snippets/s_creative_agency_features.xml',
        'views/snippets/s_creative_agency_spain.xml',
        'views/snippets/s_creative_agency_team.xml',
        'views/snippets/s_creative_agency_contactus.xml',

        # App Landing One
        'views/snippets/s_app_landing_one_banner.xml',
        'views/snippets/s_app_landing_one_about.xml',
        'views/snippets/s_app_landing_one_reporting.xml',
        'views/snippets/s_app_landing_one_counter.xml',
        'views/snippets/s_app_landing_one_why_choose.xml',
        'views/snippets/s_app_landing_one_work.xml',
        'views/snippets/s_app_landing_one_screenshots.xml',
        'views/snippets/s_app_landing_one_testimonial.xml',
        'views/snippets/s_app_landing_one_pricing_plan.xml',
        'views/snippets/s_app_landing_one_team.xml',
        'views/snippets/s_app_landing_one_download.xml',
        'views/snippets/s_app_landing_one_contactus.xml',

        # App Landing Two
        'views/snippets/s_app_landing_two_banner.xml',
        'views/snippets/s_app_landing_two_reviews.xml',
        'views/snippets/s_app_landing_two_features.xml',
        'views/snippets/s_app_landing_two_video_banner.xml',
        'views/snippets/s_app_landing_two_conversions.xml',
        'views/snippets/s_app_landing_two_steps.xml',
        'views/snippets/s_app_landing_two_productivity.xml',
        'views/snippets/s_app_landing_two_text.xml',
        'views/snippets/s_app_landing_two_pricing_plan.xml',
        'views/snippets/s_app_landing_two_questions.xml',
        'views/snippets/s_app_landing_two_community.xml',
        'views/snippets/s_app_landing_two_counter.xml',
        'views/snippets/s_app_landing_two_design.xml',
        'views/snippets/s_app_landing_two_teams.xml',
        'views/snippets/s_app_landing_two_newsletter.xml',

        #Snowboard & Ski
        'views/snippets/s_snowboard_ski_banner.xml',
        'views/snippets/s_snowboard_ski_welcome.xml',
        'views/snippets/s_snowboard_ski_skating.xml',
        'views/snippets/s_snowboard_ski_accessories.xml',
        'views/snippets/s_snowboard_ski_parallax.xml',
        'views/snippets/s_snowboard_ski_products.xml',
        'views/snippets/s_snowboard_ski_certified.xml',
        'views/snippets/s_snowboard_ski_testimonial.xml',
        'views/snippets/s_snowboard_ski_team.xml',
        'views/snippets/s_snowboard_ski_best_skiz.xml',
        'views/snippets/s_snowboard_ski_newsletter.xml',
        'views/snippets/s_snowboard_ski_brands.xml',

        # Medical
        'views/snippets/s_medical_banner.xml',
        'views/snippets/s_medical_service.xml',
        'views/snippets/s_medical_care.xml',
        'views/snippets/s_medical_prevent.xml',
        'views/snippets/s_medical_durability.xml',
        'views/snippets/s_medical_parallax_protection.xml',
        'views/snippets/s_medical_protection.xml',
        'views/snippets/s_medical_supplies.xml',
        'views/snippets/s_medical_features.xml',
        'views/snippets/s_medical_products.xml',
        'views/snippets/s_medical_about_products.xml',
        'views/snippets/s_medical_helpline.xml',

        # Cyber Security
        'views/snippets/s_cyber_security_banner.xml',
        'views/snippets/s_cyber_security_plateform.xml',
        'views/snippets/s_cyber_security_features.xml',
        'views/snippets/s_cyber_security_work.xml',
        'views/snippets/s_cyber_security_services.xml',
        'views/snippets/s_cyber_security_faq.xml',
        'views/snippets/s_cyber_security_team.xml',
        'views/snippets/s_cyber_security_clients.xml',

        # Cyber Security
        'views/snippets/s_real_estate_banner.xml',
        'views/snippets/s_real_estate_aboutus.xml',
        'views/snippets/s_real_estate_counter.xml',
        'views/snippets/s_real_estate_text.xml',
        'views/snippets/s_real_estate_properties.xml',
        'views/snippets/s_real_estate_clients.xml',

        # Travel
        'views/snippets/s_travel_banner.xml',
        'views/snippets/s_travel_holidays.xml',
        'views/snippets/s_travel_image.xml',
        'views/snippets/s_travel_discover.xml',
        'views/snippets/s_travel_services.xml',
        'views/snippets/s_travel_testimonial.xml',
        'views/snippets/s_travel_countries.xml',
        'views/snippets/s_travel_reviews.xml',
        'views/snippets/s_travel_destination.xml',
        'views/snippets/s_travel_bags.xml',

        # Yoga
        'views/snippets/s_yoga_banner.xml',
        'views/snippets/s_yoga_motivation.xml',
        'views/snippets/s_yoga_classes.xml',
        'views/snippets/s_yoga_aboutus.xml',
        'views/snippets/s_yoga_styles.xml',
        'views/snippets/s_yoga_trainers.xml',
        'views/snippets/s_yoga_testimonial.xml',
        'views/snippets/s_yoga_brands.xml',
        'views/snippets/s_yoga_newsletter.xml',
        'views/snippets/s_yoga_contactus.xml',

        # SEO
        'views/snippets/s_seo_banner.xml',
        'views/snippets/s_seo_services.xml',
        'views/snippets/s_seo_teams.xml',
        'views/snippets/s_seo_contactus.xml',
        'views/snippets/s_seo_newsletter.xml',
        'views/snippets/s_seo_marketing.xml',
        'views/snippets/s_seo_pricing_plan.xml',

        # Hotel
        'views/snippets/s_hotel_banner.xml',
        'views/snippets/s_hotel_rooms.xml',
        'views/snippets/s_hotel_welcome.xml',
        'views/snippets/s_hotel_services.xml',
        'views/snippets/s_hotel_reviews.xml',
        'views/snippets/s_hotel_address.xml',

        # Dessert
        'views/snippets/s_dessert_banner.xml',
        'views/snippets/s_dessert_services.xml',
        'views/snippets/s_dessert_aboutus.xml',
        'views/snippets/s_dessert_offers.xml',
        'views/snippets/s_dessert_product_menu.xml',
        'views/snippets/s_dessert_product_menu_two.xml',
        'views/snippets/s_dessert_testimonials.xml',
        'views/snippets/s_dessert_founder.xml',
        'views/snippets/s_dessert_images.xml',
    ],
    'demo': [
        'data/menu_data.xml',
    ],

    'assets': {
        'web._assets_primary_variables': [
            ('prepend', '/theme_vouge/static/src/scss/new_theme_variable.scss'),
            '/theme_vouge/static/src/scss/theme_variable.scss',
            'theme_vouge/static/src/scss/font_icon_mixin.scss',
        ],
        'web._assets_frontend_helpers': [
            ('prepend', '/theme_vouge/static/src/scss/bootstrap_overridden.scss'),
        ],
        'web_editor.assets_wysiwyg': [
            '/theme_vouge/static/src/js/utils.js',
        ],

        'web.assets_frontend': [
            # CSS
            '/theme_vouge/static/lib/themify-icons/themify-icons.css',
            '/theme_vouge/static/lib/fonticon/strock-gap-icons.css',
            '/theme_vouge/static/lib/icofont/icofont.css',
            '/theme_vouge/static/lib/linearicons/style.css',
            '/theme_vouge/static/lib/RemixIcon/remixicon.css',
            '/theme_vouge/static/lib/lineicons/font-css/LineIcons.css',

            '/theme_vouge/static/src/css/owl.carousel.css',
            '/theme_vouge/static/src/css/ion.rangeSlider.css',
            '/theme_vouge/static/src/css/ion.rangeSlider.skinHTML5.css',
            '/theme_vouge/static/src/scss/pro_slider.scss',
            '/theme_vouge/static/src/scss/prod_sticky.scss',

            # SCSS
            '/theme_vouge/static/src/scss/customise_model.scss',
            '/theme_vouge/static/src/scss/headers/mobile_bottom_bar.scss',
            '/theme_vouge/static/src/scss/wishlist.scss',
            '/theme_vouge/static/src/scss/megamenu.scss',
            '/theme_vouge/static/src/scss/fonts.scss',
            '/theme_vouge/static/src/scss/vouge_demo.scss',
            '/theme_vouge/static/src/scss/homepage1.scss',
            '/theme_vouge/static/src/scss/homepage2.scss',

            '/theme_vouge/static/src/scss/homepages/fashion.scss',
            '/theme_vouge/static/src/scss/homepages/fashion_accesories.scss',
            '/theme_vouge/static/src/scss/homepages/furniture.scss',
            '/theme_vouge/static/src/scss/homepages/wine.scss',
            '/theme_vouge/static/src/scss/homepages/electronic.scss',
            '/theme_vouge/static/src/scss/homepages/tools.scss',
            '/theme_vouge/static/src/scss/homepages/restaurant.scss',
            '/theme_vouge/static/src/scss/homepages/autoparts.scss',
            '/theme_vouge/static/src/scss/homepages/medical-equipement.scss',
            '/theme_vouge/static/src/scss/homepages/sports.scss',
            '/theme_vouge/static/src/scss/homepages/glasses.scss',
            '/theme_vouge/static/src/scss/homepages/spa.scss',
            '/theme_vouge/static/src/scss/homepages/grocery.scss',
            '/theme_vouge/static/src/scss/homepages/organic.scss',
            '/theme_vouge/static/src/scss/homepages/jewellery.scss',

            '/theme_vouge/static/src/scss/bussiness-pages/charity.scss',
            '/theme_vouge/static/src/scss/bussiness-pages/It-solution.scss',
            '/theme_vouge/static/src/scss/bussiness-pages/creative-agency.scss',
            '/theme_vouge/static/src/scss/bussiness-pages/app-landing.scss',
            '/theme_vouge/static/src/scss/bussiness-pages/app-landing-two.scss',
            '/theme_vouge/static/src/scss/bussiness-pages/medical.scss',
            '/theme_vouge/static/src/scss/bussiness-pages/snowboard.scss',
            '/theme_vouge/static/src/scss/bussiness-pages/cyber-security.scss',
            '/theme_vouge/static/src/scss/bussiness-pages/real-estate.scss',
            '/theme_vouge/static/src/scss/bussiness-pages/travel.scss',
            '/theme_vouge/static/src/scss/bussiness-pages/yoga.scss',
            '/theme_vouge/static/src/scss/bussiness-pages/seo.scss',
            '/theme_vouge/static/src/scss/bussiness-pages/hotel.scss',
            '/theme_vouge/static/src/scss/bussiness-pages/desserts.scss',

            '/theme_vouge/static/src/scss/footers/footer.scss',
            '/theme_vouge/static/src/scss/footers/footer4.scss',
            '/theme_vouge/static/src/scss/footers/footer5.scss',
            '/theme_vouge/static/src/scss/footers/footer6.scss',
            '/theme_vouge/static/src/scss/footers/footer7.scss',
            '/theme_vouge/static/src/scss/footers/footer8.scss',

            '/theme_vouge/static/src/scss/headers/sidebar.scss',
            '/theme_vouge/static/src/scss/headers/header.scss',
            '/theme_vouge/static/src/scss/headers/header2.scss',
            '/theme_vouge/static/src/scss/headers/header3.scss',
            '/theme_vouge/static/src/scss/headers/header4.scss',
            '/theme_vouge/static/src/scss/headers/header5.scss',
            '/theme_vouge/static/src/scss/headers/header6.scss',
            '/theme_vouge/static/src/scss/headers/header7.scss',
            '/theme_vouge/static/src/scss/headers/header8.scss',
            '/theme_vouge/static/src/scss/headers/header9.scss',
            '/theme_vouge/static/src/scss/headers/header10.scss',
            '/theme_vouge/static/src/scss/headers/header11.scss',

            '/theme_vouge/static/src/scss/similar_product_sidebar.scss',
            '/theme_vouge/static/src/scss/shop_products.scss',
            '/theme_vouge/static/src/scss/shop_product.scss',
            '/theme_vouge/static/src/scss/product_slider.scss',
            '/theme_vouge/static/src/scss/contactus.scss',
            '/theme_vouge/static/src/scss/newsletter_popup.scss',
            '/theme_vouge/static/src/scss/quick_view.scss',
            '/theme_vouge/static/src/scss/category_sidebar.scss',
            '/theme_vouge/static/src/scss/cart_sidebar.scss',
            '/theme_vouge/static/src/scss/compare_products.scss',
            '/theme_vouge/static/src/scss/shopby.scss',
            '/theme_vouge/static/src/scss/portal.scss',
            '/theme_vouge/static/src/scss/help_center.scss',
            '/theme_vouge/static/src/scss/coming-soon.scss',
            '/theme_vouge/static/src/scss/blog_page.scss',
            '/theme_vouge/static/src/scss/product_banner.scss',
            '/theme_vouge/static/src/scss/image_hotspot.scss',
            '/theme_vouge/static/src/scss/login_popup.scss',

            '/theme_vouge/static/src/scss/homepage-one.scss',
            '/theme_vouge/static/src/scss/homepage-two.scss',
            '/theme_vouge/static/src/scss/homepage-three.scss',
            '/theme_vouge/static/src/scss/homepage-four.scss',
            '/theme_vouge/static/src/scss/homepage-five.scss',
            '/theme_vouge/static/src/scss/homepage-six.scss',
            '/theme_vouge/static/src/scss/homepage-seven.scss',
            '/theme_vouge/static/src/scss/homepage-eight.scss',
            '/theme_vouge/static/src/scss/homepage-nine.scss',
            '/theme_vouge/static/src/scss/homepage-ten.scss',
            '/theme_vouge/static/src/scss/homepage-eleven.scss',
            '/theme_vouge/static/src/scss/homepage-twelve.scss',
            '/theme_vouge/static/src/scss/homepage-thirteen.scss',
            '/theme_vouge/static/src/scss/homepage-fourteen.scss',
            '/theme_vouge/static/src/scss/homepage-fifteen.scss',
            '/theme_vouge/static/src/scss/product_configurator.scss',
            '/theme_vouge/static/src/scss/category_configurator.scss',
            '/theme_vouge/static/src/scss/brand_configurator.scss',
            '/theme_vouge/static/src/scss/dynamic_configurator_snippets.scss',

            '/theme_vouge/static/src/scss/buttons/biz_button_1.scss',
            '/theme_vouge/static/src/scss/buttons/biz_button_2.scss',
            '/theme_vouge/static/src/scss/buttons/biz_button_3.scss',
            '/theme_vouge/static/src/scss/buttons/biz_button_4.scss',
            '/theme_vouge/static/src/scss/buttons/biz_button_5.scss',
            '/theme_vouge/static/src/scss/buttons/biz_button_6.scss',
            '/theme_vouge/static/src/scss/buttons/biz_button_7.scss',
            '/theme_vouge/static/src/scss/buttons/biz_button_8.scss',
            '/theme_vouge/static/src/scss/buttons/biz_button_9.scss',
            '/theme_vouge/static/src/scss/buttons/biz_button_10.scss',
            '/theme_vouge/static/src/scss/buttons/biz_button_11.scss',
            '/theme_vouge/static/src/scss/buttons/biz_button_12.scss',

            # js
            '/theme_vouge/static/src/js/owl.carousel.min.js',
            '/theme_vouge/static/src/js/bizcommon_fronted.js',
            '/theme_vouge/static/src/js/ion.rangeSlider.min.js',
            '/theme_vouge/static/src/js/common.js',
            '/theme_vouge/static/src/js/custom_config.js',
            '/theme_vouge/static/src/js/header_color_option.js',
            '/theme_vouge/static/src/js/biz_quickview.js',
            '/theme_vouge/static/src/js/product_variant.js',
            '/theme_vouge/static/src/js/user_portal.js',
            '/theme_vouge/static/src/js/portal.js',
            '/theme_vouge/static/src/js/pwebapp.js',
            '/theme_vouge/static/src/js/product_search.js',
            '/theme_vouge/static/src/js/lazyload.js',
        ],
        'website.assets_editor': [
            '/theme_vouge/static/src/js/bizcommon_editor.js',
            '/theme_vouge/static/src/js/product_banner_option.js',
            '/theme_vouge/static/src/js/image_hotspot_options.js',
            '/theme_vouge/static/src/js/icon_pack.js',
            '/theme_vouge/static/src/js/product_configurator_options.js',
            '/theme_vouge/static/src/js/category_configurator_options.js',
            '/theme_vouge/static/src/js/brand_configurator_options.js',
            '/theme_vouge/static/src/js/button_editor.js',
        ],
    },

    'live_test_url': 'https://bit.ly/demo-vouge-15',

    'images': [
        'static/description/vouge_cover.png',
        'static/description/vouge_screenshot.gif',
    ],

    'installable': True,
    'auto_install': False,
    'application': False,
    'license': 'OPL-1',
    'price': 130,
    'currency': 'EUR',
}
