from . import hr_employee_custom
from . import ebs_health_card
from . import ebs_insurance
from . import ebs_education
from . import ebs_sponsoring_dependents
from . import ebs_family_details
from . import ebs_visa_details
from . import ebs_driving_licence
from . import ebs_designation_description
from . import ebs_penalty
from . import ebs_history_experience
from . import ebs_hobbies
from . import ebs_res_partner_bank_custom
from . import ebs_fusion_document_document_custom
from . import ebs_hr_employee_e_contract
from . import ebs_workmen_compensation
from . import res_config_settings
from . import ebs_emp_residence
from . import outsourced_employee_report_config
