from odoo import api, fields, models, _

class ProductTemplate(models.Model):

    _inherit = 'product.template'

    product_country_manufacturer_id = fields.Many2one('res.country',string="Product Country Manufacturer")
    company_name_manufacturer = fields.Char("Company Name of Manufacturer")
    paetner_name_manufacturer = fields.Char("Partner Name of the Manufacturer")
    date_of_manufacturer = fields.Date("Date of Manufacturer")
    date_of_esta_company = fields.Date("Date of Establishment of Company")
    start_date_guarantee_certification = fields.Date("Start Date Guarantee/Certification")
    end_date_guarantee_certification = fields.Date("End Date Guarantee/Certification")
    certification_of_product_id = fields.Many2one('documents.document',string="Certification of Product")
    industry_of_product_id = fields.Many2one('res.partner.industry',string="Industry of Product")
    actual_cost_of_product = fields.Float(string="Actual Cost of Product")
    landing_cost_of_shipping_land = fields.Float(string="Landing cost of Shipping (Land)")
    landing_cost_of_shipping_sea = fields.Float(string="Landing cost of Shipping (Sea)")
    landing_cost_of_shipping_air = fields.Float(string="Landing cost of Shipping (Air)")
    production_timeline_to_manufacture = fields.Float(string="Production Timeline to Manufacture")
    process_delivering_the_product = fields.Char(string="Process of Delivering the Product")
    process_installation_product = fields.Char(string="Process of Installation of Product")
    letter_agency_autho_id = fields.Many2one('documents.document',string="Letter of Authority or Agency to whom it may concern")
    requirement_install_the_product = fields.Char(string="Requirement to Install the Product")
    timeline_installation = fields.Char(string="Timeline of the Installation")
    product_training_program_manual = fields.Selection([('power point','Power Point'),('presentation marketing tools','Presentation Marketing Tools')],string="Timeline of the Installation")
    vendor_manufacturing_tools = fields.Char("Vendor Manufacturing Tools")
    user_manual_product = fields.Char("User Manual of the Product")
    spare_parts_product = fields.Char("Spare Parts of the Product")
    duration_use_product = fields.Float("Duration Use of the Product")
    product_insurance_cost = fields.Float("Product Insurance Cost")
    product_operation_cost = fields.Float("Product Operation Cost")
    shelf_life_spare_parts = fields.Float("Shelf Life of the Spare Parts")
    profile_product = fields.Char("Profile of the Product (When used in the past)")
    sales_contact_person = fields.Char("Sales Contact Person")
    technical_contact_person = fields.Char("Technical Contact Person")
    marketing_contact_person = fields.Char("Marketing Contact Person")
    partner_id = fields.Many2one('res.partner',string='Partner')
    is_asset = fields.Boolean('Is Asset')
    asset_id = fields.Many2one('account.asset',string="Assets")
