{
    'name': 'Matager Account Modifier',
    'version': '15.0.5',
    'summary': 'Signup Modification',
    'description': 'Login with phone number.login verification with phone and email.',
    'category': 'Web',
    'author': '',
    'website': '',
    'depends': ['base', 'portal', 'web', 'website', 'auth_signup', 'website_sale'],
    'data': [
        'security/ir.model.access.csv',
        'data/mail_template_data.xml',
        'data/email_shop_address_template.xml',
        'data/google_api_key_data.xml',
        'views/web_login_inherit.xml',
        'views/website_my_profile.xml',
        'views/res_user_extended_view.xml',
        'views/res_partner_extended_view.xml',
        'views/signup_page_inherit_view.xml',
        'views/signup_phone_verify_view.xml',
        'views/signup_email_verify_view.xml',
        'views/web_reset_password_view_inherit.xml',
        'views/custom_request_view.xml',
        'views/custom_request_portal.xml',
        'views/shop_address_page_inherit_view.xml',
        'views/ir_config_settings_extended_view.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            # '/matager_account_modifier/static/src/js/phone_email_timer_otp.js',
            '/matager_account_modifier/static/src/js/address_search.js',
            '/matager_account_modifier/static/src/css/map_address.css',
            '/matager_account_modifier/static/src/js/phone_email_validation_profile.js',
            '/matager_account_modifier/static/src/js/phone_email_validation_signup.js',
            '/matager_account_modifier/static/src/css/phone_validation_profile.css',
        ],
    },
    'application': True,
    'installable': True,
    'auto_install': False
}
