from . import ebs_crm_service_category
from . import ebs_crm_service
from . import ebs_crm_service_stage
from . import ebs_crm_proposal
from . import account_move_custom
from . import ebs_crm_service_authority
from . import ebs_crm_pricelist
from . import ebs_crm_pricelist_category
from . import crm_lead_custom
from . import ebs_crm_service_template
from . import document_document_custom
from . import ebs_crm_service_process
from . import res_partner_custom
from . import res_config_settings_custom
from . import ebs_crm_contract_fees
from . import ebs_crm_contract_details
from . import hr_employee_custom
from . import ebs_crm_service_groups
from . import ebs_crm_service_groups_line
from . import ebs_crm_service_activity
from . import ebs_crm_sub_service_process
from . import ebs_labor_quota
from . import ebs_fusion_fees
from . import ebs_service_rules
from . import ebs_contract_proposal_fees
from . import ebs_proposal_fos_fee_structure
from . import ebs_proposal_salary_structure
from . import ebs_proposal_permit_issuance
from . import ebs_service_user_group
from . import ebs_accounts_credit_cards
from . import ebs_workflow_payment
from . import ebs_service_sequence
from . import ebs_batch_service_order
from . import mail_activity
from . import mail_message