# -*- coding: utf-8 -*-
# See LICENSE file for full copyright and licensing details
{
    'name': 'Property Management Website',
    'description': 'This module will help you to manage your real estate portfolio with Property valuation, Maintenance, Insurance, Utilities and Rent management with reminders for each KPIs.',
    'category': 'Website',
    'version': '13.0.1.0.0',
    'license': 'LGPL-3',
    'author': 'Serpent Consulting Services Pvt. Ltd.',
    'depends': ['property_management', 'base_geolocalize', 'payment_paypal', 'property_penalty', 'portal', 'website',
                'auth_signup'],
    'data': [
        'views/website_assets.xml',
        'views/assets_views.xml',
        'views/homepage_template.xml',
        'data/website_data.xml',
        'views/property_main_template.xml',
        'views/testimonials.xml',
        'views/property_login_view.xml',
        'views/rent_properties_onload.xml',
        'views/selected_property_template.xml',
        'views/suggested_property_template.xml',
        'views/sell_property_template.xml',
        'views/allpastlease_content_template.xml',
        'views/saved_sale_template.xml',
        'views/my_property_template.xml',
        'views/website_search_bar_template.xml',
        'views/website_property_pagination_template.xml',
        'views/website_property_filter.xml',
        'security/website_security.xml',
        'security/ir.model.access.csv',
    ],
    'assets': {
        'web.assets_frontend': [
            'property_website/static/lib/jquery.ui/jquery-ui.js',
            'property_website/static/lib/jquery.ui/jquery-ui.css',
            'property_website/static/src/css/style.css',
            'property_website/static/src/css/gallery-grid.css',
            'property_website/static/src/css/card.css',
            'property_website/static/src/js/google.map.js',
            'property_website/static/src/js/google_map_script.js',
            'property_website/static/src/js/pms_main.js',
            # 'property_website/static/src/js/homepage_search.js',
            'property_website/static/src/js/property_rpc.js',
            'property_website/static/src/js/validator.js',
        ],

    },
    'images': ['static/description/banner.png'],
    'application': True,
    'installable': True,
    'price': 299,
    'currency': 'EUR',
}
