from . import crm_lead_custom
from . import res_partner_custom
from . import res_partner_industry_custom
from . import crm_stage_custom
from . import mail_activity_custom
from . import res_users_custom
from . import ebs_contact_industries
from . import res_config_settings
from . import ebs_calendar_meeting_room
